const fs = require('fs');

// Load files
const en = JSON.parse(fs.readFileSync('src/i18n/locales/en.json', 'utf8'));
const auto = JSON.parse(fs.readFileSync('missing-keys-auto.json', 'utf8'));

// Deep merge (only adds keys that don't exist in target)
function deepMerge(target, source) {
  for (const key of Object.keys(source)) {
    if (source[key] && typeof source[key] === 'object' && !Array.isArray(source[key])) {
      if (!target[key] || typeof target[key] !== 'object' || Array.isArray(target[key])) {
        target[key] = {};
      }
      deepMerge(target[key], source[key]);
    } else if (!(key in target)) {
      target[key] = source[key];
    }
  }
  return target;
}

// Set a nested key value
function setKey(obj, path, value) {
  const parts = path.split('.');
  let cur = obj;
  for (let i = 0; i < parts.length - 1; i++) {
    if (!cur[parts[i]] || typeof cur[parts[i]] !== 'object') cur[parts[i]] = {};
    cur = cur[parts[i]];
  }
  cur[parts[parts.length - 1]] = value;
}

// ============================================================
// FIX: Merge duplicate common.time keys (am/pm + hourAbbr/minuteAbbr)
// ============================================================
if (!en.common.time || typeof en.common.time !== 'object') en.common.time = {};
en.common.time.am = 'AM';
en.common.time.pm = 'PM';
en.common.time.hourAbbr = 'Hr';
en.common.time.minuteAbbr = 'Min';

// ============================================================
// OVERRIDE auto-generated values with proper English text
// ============================================================
const overrides = {
  // -- Validation --
  'validation.emailInvalid': 'Please enter a valid email address',
  'validation.firstNameMin': 'First name must be at least 2 characters',
  'validation.lastNameMin': 'Last name must be at least 2 characters',
  'validation.passwordMin': 'Password must be at least 8 characters',
  'validation.passwordRequired': 'Password is required',
  'validation.passwordUppercase': 'Must include an uppercase letter',
  'validation.passwordLowercase': 'Must include a lowercase letter',
  'validation.passwordNumber': 'Must include a number',
  'validation.passwordsDoNotMatch': 'Passwords do not match',
  // -- Auth --
  'auth.errors.googleCancelled': 'Google sign-in was cancelled',
  'auth.errors.googleInitFailed': 'Failed to initialize Google sign-in',
  'auth.errors.googleLoadFailed': 'Failed to load Google sign-in',
  'auth.errors.googleNoSession': 'No active Google session found',
  'auth.errors.googlePromptFailed': 'Google sign-in prompt failed',
  'auth.errors.googleUnavailable': 'Google sign-in is currently unavailable',
  'auth.google.continueWith': 'Continue with Google',
  'auth.google.signIn': 'Sign in with Google',
  'auth.google.signUpWith': 'Sign up with Google',
  'auth.login.checkingInfo': 'Checking your information...',
  'auth.login.failed': 'Login failed. Please check your credentials.',
  'auth.login.signingIn': 'Signing in...',
  'auth.logout.message': 'You have been logged out successfully',
  'auth.signup.failed': 'Sign up failed. Please try again.',
  'auth.signup.success': 'Account created successfully!',
  'auth.verifyEmail.failed': 'Failed to send verification email',
  'auth.verifyEmail.resendButton': 'Resend Verification Email',
  'auth.resetPassword.successTitle': 'Password Reset Successful!',
  // -- Common --
  'common.actions': 'Actions',
  'common.aria.nextMonth': 'Next month',
  'common.aria.previousMonth': 'Previous month',
  'common.aria.selectDateRange': 'Select date range',
  'common.category': 'Category',
  'common.confirmLogout': 'Are you sure you want to log out?',
  'common.connecting': 'Connecting...',
  'common.copied': 'Copied to clipboard',
  'common.copy': 'Copy',
  'common.copyFailed': 'Failed to copy',
  'common.creating': 'Creating...',
  'common.currencySymbol': '$',
  'common.days.fri': 'Fri',
  'common.days.mon': 'Mon',
  'common.days.sat': 'Sat',
  'common.days.sun': 'Sun',
  'common.days.thu': 'Thu',
  'common.days.tue': 'Tue',
  'common.days.wed': 'Wed',
  'common.entryError': 'Entry Error',
  'common.finalConfirmation': 'Final Confirmation',
  'common.finish': 'Finish',
  'common.guide': 'Guide',
  'common.languages.ar': 'العربية',
  'common.languages.en': 'English',
  'common.live': 'LIVE',
  'common.loadingVideo': 'Loading video...',
  'common.location': 'Location',
  'common.locations': 'Locations',
  'common.logoAlt': 'PayMint Logo',
  'common.logout': 'Log out',
  'common.mo': '/mo',
  'common.month': 'Month',
  'common.na': 'N/A',
  'common.name': 'Name',
  'common.noData': 'No data available',
  'common.noResults': 'No results found',
  'common.note': 'Note',
  'common.password': 'Password',
  'common.print': 'Print',
  'common.privacyPolicy': 'Privacy Policy',
  'common.restoring': 'Restoring...',
  'common.role': 'Role',
  'common.saveChanges': 'Save Changes',
  'common.searchArticles': 'Search articles...',
  'common.searchPlaceholder': 'Search...',
  'common.security': 'Security',
  'common.selected': 'Selected',
  'common.settings': 'Settings',
  'common.share': 'Share',
  'common.sortByDate': 'Sort by Date',
  'common.sortByLocations': 'Sort by Locations',
  'common.sortByName': 'Sort by Name',
  'common.sortByRole': 'Sort by Role',
  'common.status': 'Status',
  'common.submitting': 'Submitting...',
  'common.system': 'System',
  'common.tip': 'Tip',
  'common.viewAll': 'View All',
  'common.website': 'Website',
  'common.welcome': 'Welcome!',
  'common.welcomeBack': 'Welcome back!',
  // -- Password Reset --
  'passwordReset.form.confirmPassword': 'Confirm Password',
  'passwordReset.form.confirmPlaceholder': 'Re-enter your password',
  'passwordReset.form.newPassword': 'New Password',
  'passwordReset.form.passwordPlaceholder': 'Enter your new password',
  'passwordReset.form.resend': 'Resend Code',
  'passwordReset.form.resetButton': 'Reset Password',
  'passwordReset.form.resetting': 'Resetting...',
  'passwordReset.form.sendCode': 'Send Code',
  'passwordReset.form.sending': 'Sending...',
  'passwordReset.form.verifyCode': 'Verify Code',
  'passwordReset.form.verifying': 'Verifying...',
  'passwordReset.messages.codeSent': 'Verification code sent to your email',
  'passwordReset.messages.codeVerified': 'Code verified successfully',
  'passwordReset.messages.enterFullCode': 'Please enter the full verification code',
  'passwordReset.messages.failedToReset': 'Failed to reset password',
  'passwordReset.messages.failedToSend': 'Failed to send verification code',
  'passwordReset.messages.invalidCode': 'Invalid verification code',
  'passwordReset.messages.passwordReset': 'Password has been reset successfully',
  'passwordReset.steps.enterCodeTitle': 'Enter Verification Code',
  'passwordReset.steps.newPasswordDesc': 'Create a strong password for your account',
  'passwordReset.steps.newPasswordTitle': 'Set New Password',
  'passwordReset.steps.successDesc': 'You can now log in with your new password.',
  'passwordReset.steps.successTitle': 'Password Reset Successful!',
  'passwordReset.steps.verifyDesc': 'Enter the email associated with your account',
  'passwordReset.steps.verifyTitle': 'Verify Your Identity',
  'passwordReset.title.account': 'Account Password Reset',
  'passwordReset.title.default': 'Reset Password',
  // -- Cookies --
  'cookies.banner.acceptAll': 'Accept All',
  'cookies.banner.description': 'We use cookies to enhance your browsing experience and analyze site traffic.',
  'cookies.banner.policyLink': 'Cookie Policy',
  'cookies.banner.preferences': 'Manage Preferences',
  'cookies.banner.rejectAll': 'Reject All',
  'cookies.banner.title': 'Cookie Consent',
  'cookies.policy.declaration': 'Cookie Declaration',
  'cookies.policy.p1': 'This website uses cookies to ensure you get the best experience.',
  'cookies.policy.p2': 'You can change your cookie preferences at any time.',
  'cookies.preferences.alwaysActive': 'Always Active',
  'cookies.preferences.manage': 'Manage Cookie Preferences',
  'cookies.preferences.save': 'Save Preferences',
  'cookies.preferences.subtitle': 'Choose which cookies you\'d like to accept.',
  'cookies.preferences.title': 'Cookie Preferences',
  'cookies.types.analytics.description': 'Help us understand how visitors interact with our website.',
  'cookies.types.analytics.title': 'Analytics Cookies',
  'cookies.types.essential.description': 'Necessary for the website to function. Cannot be switched off.',
  'cookies.types.essential.title': 'Essential Cookies',
  'cookies.types.marketing.description': 'Used to track visitors across websites for relevant ads.',
  'cookies.types.marketing.title': 'Marketing Cookies',
  // -- Contact --
  'contact.title': 'Contact Us',
  // -- Hardware --
  'hardware.tip': 'Pro Tip: All recommended hardware is fully compatible with PayMint POS.',
  // -- Landing --
  'landing.contact.terms': 'By submitting, you agree to our Terms of Service and Privacy Policy.',
  'landing.pricing.features.adminApp': 'Admin Mobile App',
  'landing.pricing.features.advancedReporting': 'Advanced Reporting & Analytics',
  'landing.pricing.features.dashboard': 'Full Dashboard Access',
  'landing.pricing.features.inventory': 'Inventory Management',
  'landing.pricing.features.pointOfSale': 'Point of Sale System',
  'landing.pricing.features.pos': 'POS System',
  'landing.pricing.features.production': 'Production & Recipes',
  'landing.pricing.features.reports': 'Reports & Analytics',
  'landing.pricing.features.staffManagement': 'Staff Management',
  'landing.pricing.features.support': 'Priority Support',
  'landing.pricing.features.unlimitedStaff': 'Unlimited Staff Accounts',
  'landing.pricing.monthlyPlan': 'Monthly Plan',
  'landing.pricing.perMonth': '/month',
  'landing.pricing.planDescription': 'Everything you need to run your business.',
  'landing.pricing.startFreeTrial': 'Start Free Trial',
  // -- Pricing (top-level) --
  'pricing.planDetails': 'Plan Details',
  'pricing.viewDetails': 'View Details',
  'pricing.whatsIncluded': "What's Included",
  // -- Dashboard --
  'dashboard.menu.billing': 'Billing',
  'dashboard.menu.overview': 'Overview',
  'dashboard.roles.access': 'Access',
  'dashboard.roles.actions': 'Actions',
  'dashboard.roles.addRole': 'Add Role',
  'dashboard.roles.created': 'Created',
  'dashboard.roles.date': 'Date',
  'dashboard.roles.deleteRole': 'Delete Role',
  'dashboard.roles.deleteTitle': 'Delete Role',
  'dashboard.roles.editRole': 'Edit Role',
  'dashboard.roles.gridView': 'Grid View',
  'dashboard.roles.listView': 'List View',
  'dashboard.roles.loading': 'Loading roles...',
  'dashboard.roles.messages.created': 'Role created successfully',
  'dashboard.roles.messages.deleted': 'Role deleted successfully',
  'dashboard.roles.messages.deleteFailed': 'Failed to delete role',
  'dashboard.roles.messages.loadFailed': 'Failed to load roles',
  'dashboard.roles.messages.noLocation': 'No location selected',
  'dashboard.roles.messages.saveFailed': 'Failed to save role',
  'dashboard.roles.messages.updated': 'Role updated successfully',
  'dashboard.roles.name': 'Name',
  'dashboard.roles.noRoles': 'No roles found',
  'dashboard.roles.noRolesDesc': 'Create a role to define team permissions.',
  'dashboard.roles.office': 'Back Office',
  'dashboard.roles.permissions': 'Permissions',
  'dashboard.roles.pos': 'POS',
  'dashboard.roles.searchPlaceholder': 'Search roles...',
  'dashboard.roles.subtitle': 'Manage team roles and permissions',
  'dashboard.roles.title': 'Roles',
  'dashboard.roles.type': 'Type',
  'dashboard.stats.live': 'LIVE',
  // -- Roles (top-level) --
  'roles.backoffice.description': 'Back office permissions for dashboard access',
  'roles.backoffice.title': 'Back Office',
  'roles.createRole': 'Create Role',
  'roles.editRole': 'Edit Role',
  'roles.form.allAllowed': 'All discounts allowed',
  'roles.form.allowAllDiscounts': 'Allow All Discounts',
  'roles.form.allowedDiscounts': 'Allowed Discounts',
  'roles.form.roleNameLabel': 'Role Name',
  'roles.form.roleNamePlaceholder': 'Enter Role Name...',
  'roles.newRole': 'New Role',
  'roles.permissions': 'Permissions',
  'roles.pos.description': 'Point of sale permissions',
  'roles.pos.title': 'POS',
  'roles.validation.atLeastOnePermission': 'At least one permission must be selected',
  // -- Orders --
  'orders.actions.refund': 'Refund',
  'orders.actions.refundOrder': 'Refund Order',
  'orders.actions.viewDetails': 'View Details',
  'orders.details.contact': 'Contact',
  'orders.details.contactTip': 'Customer contact information',
  'orders.details.customer': 'Customer',
  'orders.details.customerTip': 'Customer who placed the order',
  'orders.details.date': 'Date',
  'orders.details.dateTip': 'Order date and time',
  'orders.details.discount': 'Discount',
  'orders.details.items': 'Items',
  'orders.details.notes': 'Notes',
  'orders.details.payment': 'Payment',
  'orders.details.paymentTip': 'Payment method used',
  'orders.details.processed': 'Processed',
  'orders.details.qty': 'Qty',
  'orders.details.refundConfirmMessage': 'Are you sure you want to refund this order?',
  'orders.details.refundConfirmTitle': 'Confirm Refund',
  'orders.details.refundedBy': 'Refunded By',
  'orders.details.refundedByTip': 'Staff who processed the refund',
  'orders.details.staff': 'Staff',
  'orders.details.staffTip': 'Staff who handled the order',
  'orders.details.status': 'Status',
  'orders.details.statusTip': 'Current order status',
  'orders.details.subtotal': 'Subtotal',
  'orders.details.tax': 'Tax',
  'orders.details.title': 'Order Details',
  'orders.details.total': 'Total',
  'orders.kpi.onHold': 'On Hold',
  'orders.kpi.totalOrders': 'Total Orders',
  'orders.kpi.totalSales': 'Total Sales',
  'orders.messages.checkShiftFailed': 'Failed to check shift status',
  'orders.messages.loadFailed': 'Failed to load orders',
  'orders.messages.loading': 'Loading orders...',
  'orders.messages.noOrders': 'No orders found',
  'orders.messages.noShiftFound': 'No active shift found',
  'orders.messages.refundConfirmMessage': 'Are you sure you want to refund this order?',
  'orders.messages.refundConfirmTitle': 'Confirm Refund',
  'orders.messages.refundFailed': 'Failed to process refund',
  'orders.messages.refundReasonWeb': 'Refunded via web dashboard',
  'orders.messages.refundSuccess': 'Order refunded successfully',
  'orders.payment.deliveryApps': 'Delivery Apps',
  'orders.period': 'Period',
  'orders.reports.shifts.sales': 'Sales',
  'orders.stats.totalSales': 'Total Sales',
  'orders.table.payment': 'Payment',
  // -- Owner --
  'owner.account.accountRestored': 'Account restored successfully',
  'owner.account.activeEstBlockModal.activeLocations': 'Active Locations',
  'owner.account.activeEstBlockModal.goToLocations': 'Go to Locations',
  'owner.account.activeEstBlockModal.subtitle': 'Deactivate all locations before deleting your account.',
  'owner.account.activeEstBlockModal.title': 'Active Locations Found',
  'owner.account.brandLoginId': 'Brand Login ID',
  'owner.account.brandLoginsSubtitle': 'Access credentials for brand dashboards',
  'owner.account.dangerZoneHint': 'Once deleted, there is no going back.',
  'owner.account.deleteAccount': 'Delete Account',
  'owner.account.deleteAccountModal.confirmFinal': 'I understand this is permanent',
  'owner.account.deleteAccountModal.confirmPassword': 'Confirm your password',
  'owner.account.deleteAccountModal.deleting': 'Deleting account...',
  'owner.account.deleteAccountModal.feedbackHint': 'Your feedback helps us improve (optional)',
  'owner.account.deleteAccountModal.passwordPlaceholder': 'Enter your password',
  'owner.account.deleteAccountModal.title': 'Delete Your Account',
  'owner.account.deleteAccountModal.warning': 'This will permanently delete your account and all data.',
  'owner.account.deleteAccountModal.whyLeaving': 'Why are you leaving?',
  'owner.account.deletionFailed': 'Failed to initiate account deletion',
  'owner.account.deletionInitiated': 'Account deletion initiated',
  'owner.account.deletionScheduledHint': 'Your account will be permanently deleted after the grace period.',
  'owner.account.loading': 'Loading account...',
  'owner.account.locationLoginsSubtitle': 'Access credentials for your POS locations',
  'owner.account.noLocationsOrBrands': 'No locations or brands found',
  'owner.account.noLocationsOrBrandsHint': 'Create a location or brand to get started.',
  'owner.account.profileUpdatedVerifyEmail': 'Profile updated. Please verify your new email.',
  'owner.account.resources.aboutUs.desc': 'Learn about the team behind PayMint',
  'owner.account.resources.aboutUs.title': 'About Us',
  'owner.account.resources.privacyPolicy.desc': 'How we handle your data',
  'owner.account.resources.privacyPolicy.title': 'Privacy Policy',
  'owner.account.resources.qa.desc': 'Frequently asked questions',
  'owner.account.resources.qa.title': 'Q&A Center',
  'owner.account.resources.setupManual.desc': 'Hardware setup guide',
  'owner.account.resources.setupManual.title': 'Setup Manual',
  'owner.account.resources.subtitle': 'Helpful resources and documentation',
  'owner.account.resources.termsOfUse.desc': 'Our terms and conditions',
  'owner.account.resources.termsOfUse.title': 'Terms of Use',
  'owner.account.resources.title': 'Resources & Help',
  'owner.account.resources.userManual.desc': 'Complete guide to using PayMint',
  'owner.account.resources.userManual.title': 'User Manual',
  'owner.account.resources.videoTutorial.desc': 'Watch how to get started',
  'owner.account.resources.videoTutorial.title': 'Video Tutorial',
  'owner.account.restoreAccount': 'Restore Account',
  'owner.account.restoreMyAccount': 'Restore My Account',
  'owner.account.securityTips.neverShareOtp': 'Never share your OTP or verification codes',
  'owner.account.securityTips.title': 'Security Tips',
  'owner.account.securityTips.uniquePasswords': 'Use unique passwords for each account',
  'owner.account.securityTips.updatePeriodically': 'Update your password periodically',
  'owner.account.stats.admins': 'Admins',
  'owner.account.stats.brands': 'Brands',
  'owner.account.stats.locations': 'Locations',
  'owner.account.validation.requiredFields': 'Please fill in all required fields',
  'owner.billing.fetchFailed': 'Failed to load billing information',
  'owner.billing.subtitle': 'Manage subscription and payments',
  'owner.billing.title': 'Billing',
  'owner.brands.activeFilters': 'Active Filters',
  'owner.brands.adminLoginId': 'Admin Login ID',
  'owner.brands.adminLoginIdHint': 'Used to access the brand dashboard',
  'owner.brands.adminLoginIdPlaceholder': 'e.g. brand_admin',
  'owner.brands.adminPassword': 'Admin Password',
  'owner.brands.brand': 'Brand',
  'owner.brands.brandName': 'Brand Name',
  'owner.brands.brandNamePlaceholder': 'e.g. My Brand',
  'owner.brands.createBrandHint': 'Group multiple locations under one brand.',
  'owner.brands.createBrandSubtitle': 'Set up a new brand',
  'owner.brands.createBrandTitle': 'Create New Brand',
  'owner.brands.createFirstBrand': 'Create Your First Brand',
  'owner.brands.location': 'Location',
  'owner.brands.noBrandsFound': 'No brands found',
  'owner.brands.selectLocationsToLink': 'Select locations to link',
  'owner.brands.tryAdjustingSearch': 'Try adjusting your search or filters',
  'owner.brands.validation.loginIdMin': 'Login ID must be at least 4 characters',
  'owner.brands.validation.loginIdRegex': 'Only letters, numbers, underscores, hyphens',
  'owner.brands.validation.nameMin': 'Brand name must be at least 2 characters',
  'owner.brands.validation.passwordMin': 'Password must be at least 6 characters',
  'owner.brands.wizard.finalStepDesc': 'Select employees for global access.',
  'owner.employees.activeNow': 'Active Now',
  'owner.employees.allRoles': 'All Roles',
  'owner.employees.totalUsers': 'Total Users',
  'owner.merge.availableLocations': 'Available Locations',
  'owner.merge.brand': 'Brand',
  'owner.merge.brandCreated': 'Brand created successfully!',
  'owner.merge.brandDetailsSubtitle': 'Enter the details for your new brand',
  'owner.merge.brandName': 'Brand Name',
  'owner.merge.brandNamePlaceholder': 'Enter brand name...',
  'owner.merge.createBrand': 'Create Brand',
  'owner.merge.createFailed': 'Failed to create brand',
  'owner.merge.enterBrandName': 'Please enter a brand name',
  'owner.merge.newBrandBadge': 'NEW BRAND',
  'owner.merge.readyForNextStep': 'Ready for next step',
  'owner.merge.selectedLocations': 'Selected Locations',
  'owner.merge.selectMinLocations': 'Select at least 2 locations',
  'owner.merge.steps.details': 'Details',
  'owner.merge.steps.select': 'Select Locations',
  'owner.merge.whyMergeDesc': 'Manage staff, reports, and settings across locations from one dashboard.',
  'owner.staff.access': 'Access',
  'owner.staff.accessRights': 'Access Rights',
  'owner.staff.addStaffDesc': 'Add a new team member',
  'owner.staff.allLocations': 'All Locations',
  'owner.staff.enterPasswordPlaceholder': 'Enter your password',
  'owner.staff.noStaffDesc': 'Add your first team member to get started',
  'owner.staff.noStaffFound': 'No staff found',
  'owner.staff.passwordPlaceholder': 'Enter password',
  'owner.staff.staffRemoved': 'Staff member removed',
  'owner.staff.syncError': 'Failed to sync staff data',
  'owner.staff.undoneWarning': 'This action cannot be undone',
  'owner.staff.verifyPassword': 'Verify your password to continue',
  // -- Account (top-level) --
  'account.restoreAction': 'Restore Account',
  'account.restored': 'Account restored successfully',
  'account.restoreFailed': 'Failed to restore account',
  'account.restoring': 'Restoring...',
  // -- Brand --
  'brand.dashboard.adjustFilters': 'Adjust Filters',
  'brand.dashboard.dissolveLocation': 'Dissolve Location',
  'brand.dashboard.openDashboard': 'Open Dashboard',
  'brand.dashboard.revenue': 'Revenue',
  'brand.dashboard.share': 'Share',
  'brand.dashboard.viewDashboard': 'View Dashboard',
  // -- Chat --
  'chat.queries.giveMeTips': 'Give me some tips',
  'chat.queries.showMeReports': 'Show me my reports',
  'chat.queries.whereAreOrders': 'Where are my orders?',
  'chat.suggestions.add_product': 'Add a product',
  'chat.suggestions.contact_support': 'Contact support',
  'chat.suggestions.get_started': 'Get started',
  'chat.suggestions.manage_staff': 'Manage staff',
  'chat.suggestions.view_orders': 'View orders',
  'chat.suggestions.view_reports': 'View reports',
  // -- Onboarding --
  'onboarding.errors.failedToComplete': 'Failed to complete setup. Please try again.',
  'onboarding.location': 'Location',
  'onboarding.messages.complete': 'Setup complete! Your location is ready.',
  'onboarding.select': 'Select',
  'onboarding.step1.businessTypes.bakery': 'Bakery',
  'onboarding.step1.currencies.AED': 'AED - UAE Dirham',
  'onboarding.step1.currencies.BHD': 'BHD - Bahraini Dinar',
  'onboarding.step1.currencies.EGP': 'EGP - Egyptian Pound',
  'onboarding.step1.currencies.EUR': 'EUR - Euro',
  'onboarding.step1.currencies.GBP': 'GBP - British Pound',
  'onboarding.step1.currencies.JOD': 'JOD - Jordanian Dinar',
  'onboarding.step1.currencies.KWD': 'KWD - Kuwaiti Dinar',
  'onboarding.step1.currencies.OMR': 'OMR - Omani Rial',
  'onboarding.step1.currencies.QAR': 'QAR - Qatari Riyal',
  'onboarding.step1.currencies.SAR': 'SAR - Saudi Riyal',
  'onboarding.step1.currencies.TRY': 'TRY - Turkish Lira',
  'onboarding.step1.currencies.USD': 'USD - US Dollar',
  'onboarding.step4.adminUsernamePlaceholder': 'e.g. admin',
  'onboarding.step5.ownerPortal': 'Owner Portal',
  'onboarding.validation.locationPasswordMin': 'Password must be at least 6 characters',
  // -- Settings --
  'settings.confirm.criticalChange': 'This is a critical system change',
  'settings.danger.cancelFailed': 'Failed to cancel deletion',
  'settings.messages.loading': 'Loading settings...',
  'settings.profile.addressPlaceholder': 'Enter your business address...',
  'settings.sales.taxErrorGeneric': 'Error updating tax rate',
  'settings.sales.taxErrorRange': 'Tax rate must be between 0% and 100%',
  // -- Payment Methods --
  'paymentMethods.messages.notActive': 'This payment method is not active',
  'paymentMethods.modal.expiryPlaceholder': 'MM/YY',
  // -- Products --
  'products.form.imagePreview': 'Image Preview',
  'products.messages.addonCreated': 'Add-on created successfully',
  'products.messages.addonFailed': 'Failed to create add-on',
  // -- Categories --
  'categories.errors.failedToCreate': 'Failed to create category',
  // -- Attributes --
  'attributes.errors.deleteFailed': 'Failed to delete',
  'attributes.filters.activeFilters': 'Active Filters',
  // -- Inventory --
  'inventory.messages.deleteFailed': 'Failed to delete item',
  // -- Staff --
  'staff.form.locationLabel': 'Location Access',
  'staff.form.standardUsers': 'Standard Users',
};

// Apply overrides to auto object
for (const [dotKey, value] of Object.entries(overrides)) {
  setKey(auto, dotKey, value);
}

// ============================================================
// SUPPORT SECTION - article titles, excerpts, and content
// ============================================================
const supportOverrides = {
  'support.hero.badge': 'Help Center',
  'support.hero.searchPlaceholder': 'How can we help you?',
  'support.hero.subtitle': 'Find answers, browse articles, or reach out to our support team.',
  'support.hero.titleHighlight': 'Support',
  'support.hero.titlePart1': 'How Can We',
  'support.hero.titlePart2': 'Help You?',
  'support.categories.all': 'All Categories',
  'support.categories.billing': 'Billing & Payments',
  'support.categories.billingDesc': 'Manage your subscription, invoices, and payment methods',
  'support.categories.billingDescShort': 'Subscription & payments',
  'support.categories.bug': 'Bug Reports',
  'support.categories.bugDescShort': 'Report issues',
  'support.categories.feature': 'Feature Requests',
  'support.categories.featureDescShort': 'Suggest improvements',
  'support.categories.features': 'Features & How-To',
  'support.categories.featuresDesc': 'Learn about features and how to use them',
  'support.categories.gettingStarted': 'Getting Started',
  'support.categories.gettingStartedDesc': 'New to PayMint? Start here with setup guides',
  'support.categories.gettingStartedDescShort': 'Setup & onboarding',
  'support.categories.notFound': 'Category Not Found',
  'support.categories.notFoundDesc': 'The category you\'re looking for doesn\'t exist.',
  'support.categories.other': 'Other',
  'support.categories.otherDescShort': 'General questions',
  'support.categories.sidebarTitle': 'Categories',
  'support.categories.subtitle': 'Browse by topic',
  'support.categories.technical': 'Technical Support',
  'support.categories.technicalDesc': 'Troubleshoot technical issues',
  'support.categories.technicalDescShort': 'Troubleshooting',
  'support.categories.title': 'Help Categories',
  'support.cta.stillNeedHelp': 'Still Need Help?',
  'support.cta.stillNeedHelpDesc': 'Our support team is available to assist you.',
  'support.cta.subtitle': 'Get in touch with our support team',
  'support.cta.title': 'Contact Support',
  'support.quickLinks.community': 'Community Forum',
  'support.quickLinks.submitTicket': 'Submit a Ticket',
  'support.qa.categories.billing': 'Billing',
  'support.qa.categories.orders': 'Orders',
  'support.qa.categories.products': 'Products',
  'support.qa.categories.staff': 'Staff',
  'support.qa.categories.technical': 'Technical',
  'support.qa.needMoreHelp': 'Need more help?',
  'support.qa.noResults': 'No results found',
  'support.qa.searchPlaceholder': 'Search for answers...',
  'support.qa.subtitle': 'Find answers to common questions',
  'support.qa.tryDifferent': 'Try a different search term',
  'support.popularArticles.account': 'Managing your account',
  'support.popularArticles.establishment': 'Setting up your establishment',
  'support.popularArticles.payment': 'Configuring payments',
  'support.popularArticles.printer': 'Setting up printers',
  'support.popularArticles.reports': 'Understanding reports',
  'support.articles.allTitle': 'All Articles',
  'support.articles.backTo': 'Back to',
  'support.articles.backToHelp': 'Back to Help Center',
  'support.articles.clearFilters': 'Clear Filters',
  'support.articles.clearSearch': 'Clear Search',
  'support.articles.count': '{{count}} articles',
  'support.articles.featuredTitle': 'Featured Articles',
  'support.articles.feedbackSorry': 'Sorry to hear that. We\'ll improve this.',
  'support.articles.feedbackThanks': 'Thanks for your feedback!',
  'support.articles.helpfulNo': 'No',
  'support.articles.helpfulQuestion': 'Was this article helpful?',
  'support.articles.helpfulYes': 'Yes',
  'support.articles.notFound': 'Article Not Found',
  'support.articles.notFoundDesc': 'The article doesn\'t exist.',
  'support.articles.notFoundDescDetail': 'It may have been moved or deleted.',
  'support.articles.popular': 'Popular',
  'support.articles.read': 'Read article',
  'support.articles.related': 'Related Articles',
  'support.articles.sortBy': 'Sort by',
  'support.articles.sortPopular': 'Most Popular',
  'support.articles.sortRecent': 'Most Recent',
  'support.articles.stubContentH1': 'Getting Started',
  'support.articles.stubContentH2': 'Key Points',
  'support.articles.stubContentP1': 'This article is being written. Check back soon.',
  'support.articles.stubContentP2': 'Contact our support team for help.',
  'support.articles.stubTitle': 'Coming Soon',
  'support.articles.updated': 'Updated',
  'support.articles.viewAll': 'View All',
  'support.articles.views': 'views',
  // Article titles
  'support.articles.gs1': 'How to Create Your First Location',
  'support.articles.gs1_excerpt': 'Step-by-step guide to setting up your first business location.',
  'support.articles.gs2': 'Setting Up Your POS System',
  'support.articles.gs2_excerpt': 'Complete walkthrough for configuring your POS.',
  'support.articles.gs3': 'Adding Your First Products',
  'support.articles.gs3_excerpt': 'Learn how to add and organize products.',
  'support.articles.gs4': 'Managing Staff & Permissions',
  'support.articles.gs4_excerpt': 'Set up team members with the right access.',
  'support.articles.gs5': 'Understanding Your Dashboard',
  'support.articles.gs5_excerpt': 'Navigate your dashboard and key metrics.',
  'support.articles.gs6': 'Setting Up Payment Methods',
  'support.articles.gs6_excerpt': 'Configure accepted payment methods.',
  'support.articles.gs7': 'Creating Categories',
  'support.articles.gs7_excerpt': 'Organize your menu with categories.',
  'support.articles.gs8': 'Setting Up Receipt Printers',
  'support.articles.gs8_excerpt': 'Connect and configure receipt printers.',
  'support.articles.ft1': 'Understanding Sales Reports',
  'support.articles.ft1_excerpt': 'Deep dive into sales analytics.',
  'support.articles.ft2': 'Managing Inventory & Stock',
  'support.articles.ft2_excerpt': 'Track stock levels and alerts.',
  'support.articles.ft3': 'Customer Loyalty Programs',
  'support.articles.ft3_excerpt': 'Set up loyalty and rewards.',
  'support.articles.ft4': 'Configuring Discounts',
  'support.articles.ft4_excerpt': 'Create and manage discounts.',
  'support.articles.ft5': 'Multi-Location Management',
  'support.articles.ft5_excerpt': 'Manage multiple locations.',
  'support.articles.ft6': 'Staff Performance Tracking',
  'support.articles.ft6_excerpt': 'Monitor staff sales performance.',
  'support.articles.ft7': 'Add-Ons & Modifiers',
  'support.articles.ft7_excerpt': 'Create product add-ons.',
  'support.articles.ft8': 'Recipe Management',
  'support.articles.ft8_excerpt': 'Track ingredient costs.',
  'support.articles.ft9': 'Cash Management',
  'support.articles.ft9_excerpt': 'Track cash flow with balance reports.',
  'support.articles.ft10': 'Brand Management',
  'support.articles.ft10_excerpt': 'Group locations into brands.',
  'support.articles.bl1': 'Subscription Plans & Pricing',
  'support.articles.bl1_excerpt': 'Understanding pricing options.',
  'support.articles.bl2': 'Managing Payment Cards',
  'support.articles.bl2_excerpt': 'Add, update, or remove cards.',
  'support.articles.bl3': 'Invoice & Billing History',
  'support.articles.bl3_excerpt': 'View and download invoices.',
  'support.articles.bl4': 'Canceling Your Subscription',
  'support.articles.bl4_excerpt': 'How to cancel or pause.',
  'support.articles.bl5': 'Free Trial Guide',
  'support.articles.bl5_excerpt': 'About your free trial.',
  'support.articles.bl6': 'Upgrading Your Plan',
  'support.articles.bl6_excerpt': 'How to upgrade.',
  'support.articles.bl7': 'Refund Policy',
  'support.articles.bl7_excerpt': 'Our refund and cancellation policy.',
  'support.articles.bl8': 'Payment Methods Accepted',
  'support.articles.bl8_excerpt': 'Accepted payment methods.',
  'support.articles.tc1': 'Initial Setup Checklist',
  'support.articles.tc1_excerpt': 'Complete setup checklist.',
  'support.articles.tc2': 'Troubleshooting Printer Issues',
  'support.articles.tc2_excerpt': 'Fix common printer problems.',
  'support.articles.tc3': 'Internet Connectivity',
  'support.articles.tc3_excerpt': 'What to do when you lose connection.',
  'support.articles.tc4': 'App Not Loading',
  'support.articles.tc4_excerpt': 'Steps to fix loading issues.',
  'support.articles.tc5': 'Data Sync Issues',
  'support.articles.tc5_excerpt': 'Resolving sync problems.',
  'support.articles.tc6': 'Browser Compatibility',
  'support.articles.tc6_excerpt': 'Supported browsers.',
  'support.articles.tc7': 'Security Best Practices',
  'support.articles.tc7_excerpt': 'Keep your account secure.',
  'support.articles.tc8': 'Account Recovery',
  'support.articles.tc8_excerpt': 'Recover your account.',
  'support.articles.tc9': 'API Integration Guide',
  'support.articles.tc9_excerpt': 'Integrate using our API.',
  'support.articles.tc10': 'Performance Optimization',
  'support.articles.tc10_excerpt': 'Improve POS performance.',
  // New ticket
  'support.newTicket.addFiles': 'Add Files',
  'support.newTicket.attachmentLimit': 'Max 3 files, 5MB each',
  'support.newTicket.categoryLabel': 'Category',
  'support.newTicket.descriptionLabel': 'Description',
  'support.newTicket.descriptionPlaceholder': 'Describe your issue in detail...',
  'support.newTicket.error': 'Failed to submit ticket',
  'support.newTicket.errors.category': 'Please select a category',
  'support.newTicket.errors.description': 'Description is required',
  'support.newTicket.errors.descriptionLength': 'Description must be at least 20 characters',
  'support.newTicket.errors.subject': 'Subject is required',
  'support.newTicket.errors.subjectLength': 'Subject must be at least 5 characters',
  'support.newTicket.priorityLabel': 'Priority',
  'support.newTicket.privacyAgreement': 'By submitting, you agree to our Privacy Policy',
  'support.newTicket.subjectLabel': 'Subject',
  'support.newTicket.subjectPlaceholder': 'Brief summary of your issue...',
  'support.newTicket.submit': 'Submit Ticket',
  'support.newTicket.subtitle': 'Fill out the form and our team will get back to you',
  'support.newTicket.success': 'Ticket submitted successfully!',
  'support.newTicket.title': 'Submit a Support Ticket',
  // Tickets
  'support.tickets.attachFile': 'Attach File',
  'support.tickets.attachments': 'Attachments',
  'support.tickets.conversation': 'Conversation',
  'support.tickets.created': 'Created',
  'support.tickets.createFirst': 'Submit your first ticket to get help',
  'support.tickets.id': 'Ticket ID',
  'support.tickets.lastUpdated': 'Last Updated',
  'support.tickets.markResolved': 'Mark as Resolved',
  'support.tickets.mock.desc1': 'I\'m having trouble connecting my receipt printer.',
  'support.tickets.mock.reply1': 'Have you tried re-pairing via Bluetooth?',
  'support.tickets.mock.reply2': 'Yes, still shows as disconnected.',
  'support.tickets.mock.reply3': 'Can you share your device and printer model?',
  'support.tickets.mock.subject1': 'Receipt printer not connecting',
  'support.tickets.myTickets': 'My Tickets',
  'support.tickets.new': 'New Ticket',
  'support.tickets.newLabel': 'New',
  'support.tickets.notFound': 'Ticket not found',
  'support.tickets.notFoundSearch': 'No tickets match your search',
  'support.tickets.noTicketsYet': 'No tickets yet',
  'support.tickets.priority.high': 'High',
  'support.tickets.priority.highDesc': 'Major feature is broken',
  'support.tickets.priority.low': 'Low',
  'support.tickets.priority.lowDesc': 'Minor issue or question',
  'support.tickets.priority.medium': 'Medium',
  'support.tickets.priority.mediumDesc': 'Feature impaired, workaround exists',
  'support.tickets.priority.urgent': 'Urgent',
  'support.tickets.priority.urgentDesc': 'System down or data loss',
  'support.tickets.priorityLabel': 'Priority',
  'support.tickets.replyPlaceholder': 'Type your reply...',
  'support.tickets.resolvedQuestion': 'Has your issue been resolved?',
  'support.tickets.sarah': 'Sarah (Support)',
  'support.tickets.searchPlaceholder': 'Search tickets...',
  'support.tickets.sendReply': 'Send Reply',
  'support.tickets.stats.inProgress': 'In Progress',
  'support.tickets.stats.open': 'Open',
  'support.tickets.stats.resolved': 'Resolved',
  'support.tickets.status.closed': 'Closed',
  'support.tickets.status.inProgress': 'In Progress',
  'support.tickets.status.open': 'Open',
  'support.tickets.status.resolved': 'Resolved',
  'support.tickets.statusLabel': 'Status',
  'support.tickets.subtitle': 'Track and manage support requests',
  'support.tickets.toClose': 'Close Ticket',
  'support.tickets.updated': 'Updated',
  'support.tickets.you': 'You',
};

for (const [dotKey, value] of Object.entries(supportOverrides)) {
  setKey(auto, dotKey, value);
}

// ============================================================
// LEGAL CONTENT
// ============================================================
const legalOverrides = {
  'legal.privacy.intro': 'Your privacy matters to us. This Privacy Policy explains how PayMint collects, uses, and protects your information.',
  'legal.privacy.agreement': 'By using our services, you agree to this policy.',
  'legal.privacy.branch.b1': 'Cloud-hosted infrastructure in North America and Europe',
  'legal.privacy.branch.b2': 'Mobile applications for iOS and Android',
  'legal.privacy.branch.b3': 'Web-based dashboard and admin portal',
  'legal.privacy.changes.desc': 'We may update this Privacy Policy from time to time.',
  'legal.privacy.children.desc': 'Our services are not intended for children under 16.',
  'legal.privacy.contact.desc': 'Contact us at privacy@PayMint.app',
  'legal.privacy.cookies.c1': 'Essential cookies for authentication',
  'legal.privacy.cookies.c2': 'Analytics cookies for usage patterns',
  'legal.privacy.cookies.c3': 'Preference cookies for your settings',
  'legal.privacy.cookies.manage': 'Manage preferences via Cookie Settings.',
  'legal.privacy.fields.analytics': 'Usage analytics',
  'legal.privacy.fields.billingAddress': 'Billing address',
  'legal.privacy.fields.businessInfo': 'Business name, type, and address',
  'legal.privacy.fields.cardDetails': 'Payment card details (PCI-compliant)',
  'legal.privacy.fields.cookies': 'Cookie and tracking data',
  'legal.privacy.fields.credentials': 'Login credentials (encrypted)',
  'legal.privacy.fields.deviceInfo': 'Device and browser information',
  'legal.privacy.fields.email': 'Email address',
  'legal.privacy.fields.fullName': 'Full name',
  'legal.privacy.fields.ipAddress': 'IP address',
  'legal.privacy.fields.loyalty': 'Loyalty and rewards data',
  'legal.privacy.fields.phone': 'Phone number',
  'legal.privacy.fields.products': 'Product and inventory data',
  'legal.privacy.fields.sales': 'Sales and transaction data',
  'legal.privacy.fields.staff': 'Staff and employee information',
  'legal.privacy.fields.transactionIds': 'Transaction identifiers',
  'legal.privacy.fields.usageLogs': 'Feature usage logs',
  'legal.privacy.international.desc': 'Your data may be transferred internationally with appropriate safeguards.',
  'legal.privacy.retention.deletionRequest': 'Request deletion at any time. Processed within 30 days.',
  'legal.privacy.retention.r1': 'Active data: retained during account lifetime',
  'legal.privacy.retention.r2': 'Financial records: 7 years (legal requirement)',
  'legal.privacy.retention.r3': 'Analytics: anonymized, up to 2 years',
  'legal.privacy.rights.contact': 'Contact privacy@PayMint.app to exercise your rights.',
  'legal.privacy.rights.ri1': 'Access: Request a copy of your data',
  'legal.privacy.rights.ri2': 'Correction: Update inaccurate information',
  'legal.privacy.rights.ri3': 'Deletion: Request data removal',
  'legal.privacy.rights.ri4': 'Portability: Receive data in portable format',
  'legal.privacy.sections.s1_desc': 'We collect information you provide directly.',
  'legal.privacy.sections.s1_1_desc': 'Account registration information',
  'legal.privacy.sections.s1_2_desc': 'Business details',
  'legal.privacy.sections.s1_2_note': 'We only collect necessary information.',
  'legal.privacy.sections.s1_3_desc': 'Transaction and payment data',
  'legal.privacy.sections.s1_4_desc': 'Support communications',
  'legal.privacy.sections.s2_desc': 'We use your information to provide and improve our services.',
  'legal.privacy.sections.s3_desc': 'We implement industry-standard security measures.',
  'legal.privacy.sections.s4_desc': 'We do not sell your personal information.',
  'legal.privacy.sections.s5_desc': 'You have the right to access, correct, delete, or export your data.',
  'legal.privacy.sections.s6_desc': 'We retain data only as long as necessary.',
  'legal.privacy.sections.s7_desc': 'We use cookies to enhance your experience.',
  'legal.privacy.sections.s8_desc': 'Contact us at privacy@PayMint.app',
  'legal.privacy.security.noAbsoluteSecurity': 'No electronic method is 100% secure.',
  'legal.privacy.security.sec1': 'AES-256 encryption for data at rest',
  'legal.privacy.security.sec2': 'TLS 1.3 for data in transit',
  'legal.privacy.security.sec3': 'Regular security audits',
  'legal.privacy.security.sec4': 'SOC 2 Type II compliance',
  'legal.privacy.sharing.obligation': 'We may disclose information if required by law.',
  'legal.privacy.sharing.sh1': 'Payment processors',
  'legal.privacy.sharing.sh2': 'Cloud infrastructure providers',
  'legal.privacy.sharing.sh3': 'Analytics providers',
  'legal.privacy.usage.noSell': 'We do not sell your personal information.',
  'legal.privacy.usage.u1': 'Provide POS services',
  'legal.privacy.usage.u2': 'Process transactions',
  'legal.privacy.usage.u3': 'Send notifications',
  'legal.privacy.usage.u4': 'Respond to support requests',
  'legal.privacy.usage.u5': 'Analyze and improve services',
  'legal.privacy.usage.u6': 'Detect fraud',
  'legal.privacy.usage.u7': 'Comply with legal obligations',
  'legal.privacy.usage.u8': 'Personalize your experience',
  'legal.terms.intro': 'These Terms govern your use of the PayMint platform.',
  'legal.terms.availability.desc': 'We strive for 99.9% uptime but cannot guarantee uninterrupted access.',
  'legal.terms.contact.desc': 'Contact legal@PayMint.app for questions.',
  'legal.terms.ip.desc': 'All content is owned by PayMint LLC and protected by IP laws.',
  'legal.terms.law.desc': 'Governed by the laws of the State of Delaware.',
  'legal.terms.liability.desc': 'PayMint shall not be liable for indirect or consequential damages.',
  'legal.terms.payments.p1': 'Subscription fees are billed monthly. Fees are non-refundable.',
  'legal.terms.payments.p2': 'We may change pricing with 30 days\' notice.',
  'legal.terms.privacy.p1': 'Your use is also governed by our Privacy Policy.',
  'legal.terms.privacy.p2': 'You consent to data collection as described in our Privacy Policy.',
  'legal.terms.responsibilities.accuracy': 'You are responsible for accuracy of information provided.',
  'legal.terms.responsibilities.intro': 'As a user, you agree to:',
  'legal.terms.responsibilities.r1': 'Maintain account security',
  'legal.terms.responsibilities.r2': 'Use services lawfully',
  'legal.terms.responsibilities.r3': 'Not reverse engineer our systems',
  'legal.terms.termination.desc': 'We may terminate access if you breach these terms.',
  'legal.terms.use.u1': 'You must be at least 18 years old',
  'legal.terms.use.u2': 'You are responsible for all account activity',
  'legal.cookies.cards.advertisingDesc': 'Used for targeted ads and campaign measurement.',
  'legal.cookies.cards.analyticsDesc': 'Help us understand visitor interactions.',
  'legal.cookies.cards.essentialDesc': 'Required for the website to function.',
  'legal.cookies.content.control_1': 'Control cookies through your browser settings.',
  'legal.cookies.content.control_2': 'Disabling cookies may affect functionality.',
  'legal.cookies.content.fb': 'Facebook Pixel',
  'legal.cookies.content.fbDesc': 'Advertising measurement on Facebook.',
  'legal.cookies.content.ga': 'Google Analytics',
  'legal.cookies.content.gaDesc': 'Anonymous statistics about website usage.',
  'legal.cookies.content.questionsDesc': 'Contact privacy@PayMint.app for questions.',
  'legal.cookies.content.thirdParty_1': 'We use the following third-party services:',
  'legal.cookies.content.updates_1': 'We may update this Cookie Policy periodically.',
  'legal.cookies.content.updates_2': 'Changes will be posted on this page.',
  'legal.cookies.content.whatAre_1': 'Cookies are small text files stored on your device.',
  'legal.cookies.content.whatAre_2': 'They help websites work more efficiently.',
  'legal.cookies.content.whyUse_1': 'We use cookies to ensure proper functionality and improve your experience.',
};

for (const [dotKey, value] of Object.entries(legalOverrides)) {
  setKey(auto, dotKey, value);
}

// ============================================================
// ARTICLE CONTENT (detailed articles gs1, gs2, ft1, bl2, tc1)
// ============================================================
const articleContent = {
  'support.articles.gs1.h1': 'Creating Your First Location',
  'support.articles.gs1.h2': 'Prerequisites',
  'support.articles.gs1.h3': 'Step-by-Step Guide',
  'support.articles.gs1.h4': 'Location Details',
  'support.articles.gs1.h5': 'Payment Setup',
  'support.articles.gs1.h6': 'POS Login Credentials',
  'support.articles.gs1.h7': 'Your Personal Login',
  'support.articles.gs1.li1_label': 'Active PayMint Account',
  'support.articles.gs1.li1_desc': 'You need a registered PayMint account.',
  'support.articles.gs1.li2_label': 'Business Information',
  'support.articles.gs1.li2_desc': 'Have your business name, type, and address ready.',
  'support.articles.gs1.li3_label': 'Payment Method',
  'support.articles.gs1.li3_desc': 'A valid card for subscription payments.',
  'support.articles.gs1.li4_label': 'Staff Details',
  'support.articles.gs1.li4_desc': 'Names and roles for staff members.',
  'support.articles.gs1.p1': 'Creating your first location is the first step to getting started with PayMint.',
  'support.articles.gs1.p2': 'Follow this guide to set up your business location in minutes.',
  'support.articles.gs1.p3': 'Enter your business name, select your type, and choose your currency.',
  'support.articles.gs1.p4': 'Choose a payment plan or start the 7-day free trial.',
  'support.articles.gs1.p5': 'Create a unique Location ID and password for your POS app.',
  'support.articles.gs1.p6': 'Set up your personal admin credentials.',
  'support.articles.gs1.p7': 'Your location is now ready. Download the POS app to start selling.',
  'support.articles.gs2.h1': 'Setting Up Your POS System',
  'support.articles.gs2.h2': 'System Requirements',
  'support.articles.gs2.h3': 'Installation Steps',
  'support.articles.gs2.h4': 'Configuration',
  'support.articles.gs2.h5': 'Adding Products',
  'support.articles.gs2.h6': 'Testing Your Setup',
  'support.articles.gs2.li1_label': 'Download the App',
  'support.articles.gs2.li1_desc': 'Get the PayMint POS app from your app store.',
  'support.articles.gs2.li2_label': 'Tablet or iPad',
  'support.articles.gs2.li2_desc': 'Any modern tablet running Android 8+ or iOS 14+.',
  'support.articles.gs2.li3_label': 'Internet Connection',
  'support.articles.gs2.li3_desc': 'Stable Wi-Fi for initial setup and syncing.',
  'support.articles.gs2.li4_label': 'Receipt Printer',
  'support.articles.gs2.li4_desc': 'Optional Bluetooth or USB thermal printer.',
  'support.articles.gs2.li5': 'Open the app and enter your Location ID',
  'support.articles.gs2.li6': 'Enter the location password',
  'support.articles.gs2.li7': 'Log in with your admin credentials',
  'support.articles.gs2.li8_label': 'Set Up Tax Rate',
  'support.articles.gs2.li8_desc': 'Configure tax in Settings > Sales.',
  'support.articles.gs2.li9_label': 'Configure Receipts',
  'support.articles.gs2.li9_desc': 'Customize receipt layout in Settings > Receipts.',
  'support.articles.gs2.li10_label': 'Add Payment Methods',
  'support.articles.gs2.li10_desc': 'Set up accepted payment types.',
  'support.articles.gs2.li11': 'Add your first category',
  'support.articles.gs2.li12': 'Create your first product',
  'support.articles.gs2.li13': 'Set prices and descriptions',
  'support.articles.gs2.li14': 'Place a test order',
  'support.articles.gs2.li15': 'Print a test receipt',
  'support.articles.gs2.li16': 'Verify payment processing',
  'support.articles.gs2.li17': 'Check the dashboard for sales',
  'support.articles.gs2.li18': 'Test staff login',
  'support.articles.gs2.p1': 'This guide walks you through POS setup.',
  'support.articles.gs2.p2': 'Make sure you have the following:',
  'support.articles.gs2.p3': 'Follow these steps to install the app.',
  'support.articles.gs2.p4': 'Configure these essential settings:',
  'support.articles.gs2.p5': 'Start building your menu by adding products.',
  'support.articles.gs2.p6': 'Run these tests to verify everything works.',
  'support.articles.ft1.h1': 'Understanding Your Sales Reports',
  'support.articles.ft1.h2': 'Report Types',
  'support.articles.ft1.h3': 'Sales Summary',
  'support.articles.ft1.h4': 'Sales by Items',
  'support.articles.ft1.h5': 'Sales by Staff',
  'support.articles.ft1.h6': 'Shift Reports',
  'support.articles.ft1.h7': 'Tips for Reports',
  'support.articles.ft1.type1_label': 'Sales Summary',
  'support.articles.ft1.type1_desc': 'Overview of total sales, refunds, and revenue.',
  'support.articles.ft1.type2_label': 'Sales by Items',
  'support.articles.ft1.type2_desc': 'See which products sell best.',
  'support.articles.ft1.type3_label': 'Sales by Staff',
  'support.articles.ft1.type3_desc': 'Track individual staff performance.',
  'support.articles.ft1.type4_label': 'Shift Reports',
  'support.articles.ft1.type4_desc': 'Review shift-level data and variances.',
  'support.articles.ft1.type5_label': 'Payment Reports',
  'support.articles.ft1.type5_desc': 'Analyze payment distribution.',
  'support.articles.ft1.type6_label': 'Discount Reports',
  'support.articles.ft1.type6_desc': 'Monitor discount usage.',
  'support.articles.ft1.li1_desc': 'Total sales amount',
  'support.articles.ft1.li1_label': 'Total Sales',
  'support.articles.ft1.li2_desc': 'Net revenue after refunds',
  'support.articles.ft1.li2_label': 'Net Revenue',
  'support.articles.ft1.li3_desc': 'Total refunds processed',
  'support.articles.ft1.li3_label': 'Refunds',
  'support.articles.ft1.li4_desc': 'Tax collected',
  'support.articles.ft1.li4_label': 'Tax',
  'support.articles.ft1.li5': 'Filter by date range, staff, or payment type',
  'support.articles.ft1.li6': 'Use charts to visualize trends',
  'support.articles.ft1.li7': 'Export as CSV for analysis',
  'support.articles.ft1.li8': 'Compare different time periods',
  'support.articles.ft1.li9': 'Check cash gap report for discrepancies',
  'support.articles.ft1.li10': 'Review peak hours for staffing',
  'support.articles.ft1.li11': 'Track daily trends to identify patterns',
  'support.articles.ft1.li12': 'Use staff reports for recognition',
  'support.articles.ft1.li13': 'Monitor discount usage',
  'support.articles.ft1.li14': 'Set up regular export schedules',
  'support.articles.ft1.li15': 'Compare week-over-week performance',
  'support.articles.ft1.p1': 'PayMint provides comprehensive sales reporting.',
  'support.articles.ft1.p2': 'Access reports from Dashboard > Sales and Reporting.',
  'support.articles.ft1.p3': 'The sales summary gives you a bird\'s-eye view.',
  'support.articles.ft1.p4': 'Drill down into individual product performance.',
  'support.articles.ft1.p5': 'Use staff reports to track productivity.',
  'support.articles.ft1.p6': 'Review shift data for cash handling.',
  'support.articles.bl2.h1': 'Managing Your Payment Cards',
  'support.articles.bl2.h2': 'Adding a New Card',
  'support.articles.bl2.h3': 'Setting a Default Card',
  'support.articles.bl2.h4': 'Removing a Card',
  'support.articles.bl2.h5': 'Troubleshooting',
  'support.articles.bl2.h6': 'Security',
  'support.articles.bl2.li1': 'Navigate to Owner Portal > Billing',
  'support.articles.bl2.li2': 'Click \'Add Card\'',
  'support.articles.bl2.li3': 'Enter your card details',
  'support.articles.bl2.li4': 'Click \'Save\' to add the card',
  'support.articles.bl2.li5': 'Go to the Billing section',
  'support.articles.bl2.li6': 'Find the card you want as default',
  'support.articles.bl2.li7': 'Click \'Set as Default\'',
  'support.articles.bl2.li8': 'The card will be used for future charges',
  'support.articles.bl2.li9': 'You cannot remove a card linked to active subscriptions',
  'support.articles.bl2.li10': 'Go to the Billing section',
  'support.articles.bl2.li11': 'Find the card to remove',
  'support.articles.bl2.li12': 'Click \'Delete Card\'',
  'support.articles.bl2.li13': 'Confirm the deletion',
  'support.articles.bl2.li14': 'If your card is declined, verify the details',
  'support.articles.bl2.li15': 'Ensure your card has not expired',
  'support.articles.bl2.li16': 'Contact your bank if the issue persists',
  'support.articles.bl2.li17': 'Try adding a different card',
  'support.articles.bl2.li18': 'All card data is encrypted with AES-256',
  'support.articles.bl2.li19': 'We never store your full card number',
  'support.articles.bl2.li20': 'Payments processed via PCI-compliant partners',
  'support.articles.bl2.li21': 'You can remove cards at any time',
  'support.articles.bl2.note_label': 'Important',
  'support.articles.bl2.note_desc': 'Keep at least one valid payment method to avoid service interruption.',
  'support.articles.bl2.p1': 'This guide covers managing payment cards.',
  'support.articles.bl2.p2': 'Follow these steps to add a new card:',
  'support.articles.bl2.p3': 'Your default card is charged for subscriptions.',
  'support.articles.tc1.h1': 'Initial Setup Checklist',
  'support.articles.tc1.h2': 'Before You Start',
  'support.articles.tc1.h3': 'Account Setup',
  'support.articles.tc1.h4': 'Location Configuration',
  'support.articles.tc1.h5': 'POS Setup',
  'support.articles.tc1.step1_label': 'Create Your Account',
  'support.articles.tc1.step1_desc': 'Sign up and verify your email.',
  'support.articles.tc1.step2_label': 'Add Your First Location',
  'support.articles.tc1.step2_desc': 'Set up your business location.',
  'support.articles.tc1.step3_label': 'Configure Payment',
  'support.articles.tc1.step3_desc': 'Add a card or start free trial.',
  'support.articles.tc1.step4_label': 'Set Up POS',
  'support.articles.tc1.step4_desc': 'Download the app and log in.',
  'support.articles.tc1.step5_label': 'Add Products',
  'support.articles.tc1.step5_desc': 'Create categories and add products.',
  'support.articles.tc1.li1': 'A valid email address',
  'support.articles.tc1.li2': 'Business information',
  'support.articles.tc1.li3': 'A payment card',
  'support.articles.tc1.li4': 'A tablet or iPad',
  'support.articles.tc1.li5': 'Receipt printer (optional)',
  'support.articles.tc1.li6': 'Stable internet connection',
  'support.articles.tc1.li7': 'Staff names and roles',
  'support.articles.tc1.a1_1': 'Register at PayMint.app',
  'support.articles.tc1.a1_2': 'Verify your email',
  'support.articles.tc1.a1_3': 'Complete your profile',
  'support.articles.tc1.a2_1': 'Enter location details',
  'support.articles.tc1.a2_2': 'Set up payment',
  'support.articles.tc1.a3_1': 'Download the POS app',
  'support.articles.tc1.a3_2': 'Log in with Location ID',
  'support.articles.tc1.a3_3': 'Configure and add products',
  'support.articles.tc1.p1': 'Complete checklist for initial setup.',
  'support.articles.tc1.p2': 'Make sure you have the following ready:',
  'support.articles.tc1.p3': 'Follow these steps:',
  'support.articles.tc1.q1': 'Setup takes under 30 minutes.',
  'support.articles.tc1.q2': 'Yes, you can copy settings from existing locations.',
  'support.articles.tc1.q3': 'No special hardware needed.',
};

for (const [dotKey, value] of Object.entries(articleContent)) {
  setKey(auto, dotKey, value);
}

// ============================================================
// COMMUNITY content
// ============================================================
const communityOverrides = {
  'community.discussions.featured_1.title': 'Best practices for managing multiple locations',
  'community.discussions.featured_2.title': 'How we reduced checkout time by 40%',
  'community.discussions.featured_3.title': 'Integrating PayMint with our inventory system',
  'community.discussions.item_1.title': 'Best practices for managing multiple locations',
  'community.discussions.item_1.excerpt': 'I recently expanded to 3 locations and looking for tips...',
  'community.discussions.item_2.title': 'How we reduced checkout time by 40%',
  'community.discussions.item_2.excerpt': 'After optimizing our menu layout and training staff...',
  'community.discussions.item_3.title': 'Integrating PayMint with our inventory system',
  'community.discussions.item_3.excerpt': 'Has anyone successfully integrated PayMint with third-party inventory?',
  'community.discussions.item_4.title': 'Custom receipt templates - is it possible?',
  'community.discussions.item_4.excerpt': 'I want to add our logo and customize receipt footer...',
  'community.discussions.item_5.title': 'Setting up loyalty points for coffee shop',
  'community.discussions.item_5.excerpt': 'Looking for advice on loyalty program setup...',
  'community.guides.all': 'All Guides',
  'community.guides.item_1.title': 'Complete Setup Guide for New Users',
  'community.guides.item_2.title': 'Optimizing Your Menu Layout',
  'community.guides.item_3.title': 'Understanding Sales Reports',
  'community.guides.item_4.title': 'Employee Management Best Practices',
  'community.hub.search_placeholder': 'Search discussions, ideas, or guides...',
  'community.ideas.all': 'All Ideas',
  'community.ideas.item_1.title': 'Dark mode for POS tablet app',
  'community.ideas.item_1.description': 'A dark mode would reduce eye strain in dim environments.',
  'community.ideas.item_2.title': 'Multiple receipt printers per station',
  'community.ideas.item_2.description': 'Allow connecting multiple printers to a single tablet.',
  'community.ideas.item_3.title': 'Customer-facing display support',
  'community.ideas.item_3.description': 'Secondary display showing order details to customers.',
  'community.ideas.item_4.title': 'Offline mode improvements',
  'community.ideas.item_4.description': 'Better offline functionality with auto-sync.',
  'community.ideas.item_5.title': 'Table management & reservations',
  'community.ideas.item_5.description': 'Built-in table layout editor and reservation system.',
  'community.ideas.item_6.title': 'QR code ordering for customers',
  'community.ideas.item_6.description': 'Let customers scan QR code to view menu and order.',
};

for (const [dotKey, value] of Object.entries(communityOverrides)) {
  setKey(auto, dotKey, value);
}

// ============================================================
// MERGE auto (with overrides) INTO en.json
// ============================================================
deepMerge(en, auto);

// Write updated en.json
fs.writeFileSync(
  'src/i18n/locales/en.json',
  JSON.stringify(en, null, 2) + '\n',
  'utf8'
);

// Count keys
function countKeys(obj) {
  let c = 0;
  for (const v of Object.values(obj)) {
    if (v && typeof v === 'object' && !Array.isArray(v)) c += countKeys(v);
    else c++;
  }
  return c;
}

console.log('en.json updated successfully');
console.log('Total keys:', countKeys(en));
