export const AppStrings = {
  BRAND: {
    NAME: "PayMint",
    TAGLINE: "Enterprise",
    VERSION: "v2.0",
    COPYRIGHT: "© 2026 PayMint. All rights reserved.",
  },
  COMMON: {
    LOADING: "Loading...",
    PROCESSING: "Processing...",
    SAVING: "Saving...",
    SAVE: "Save",
    CANCEL: "Cancel",
    DELETE: "Delete",
    EDIT: "Edit",
    UPDATE: "Update",
    CREATE: "Create",
    ADD: "Add",
    NEW: "New",
    SEARCH: "Search...",
    FILTER: "Filters",
    EXPORT: "Export",
    IMPORT: "Import",
    BACK: "Back",
    NEXT: "Next",
    CONFIRM: "Confirm",
    CONTINUE: "Continue",
    SUBMIT: "Submit",
    RESET: "Reset",
    CLOSE: "Close",
    DONE: "Done",
    VIEW: "View",
    DETAILS: "Details",
    ACTIONS: "Actions",
    OPTIONAL: "(Optional)",
    REQUIRED: "*",
    SUCCESS: "Success",
    ERROR: "Error",
    WARNING: "Warning",
    INFO: "Info",
    NO_RESULTS: "No results found",
    NO_DATA: "No data available",
    EMPTY_STATE: "Nothing to see here yet",
    COMING_SOON: "Coming Soon",
  },
  STATUS: {
    ACTIVE: "Active",
    INACTIVE: "Inactive",
    PENDING: "Pending",
    COMPLETED: "Completed",
    CANCELLED: "Cancelled",
    REFUNDED: "Refunded",
    FAILED: "Failed",
    PAID: "Paid",
    UNPAID: "Unpaid",
    OVERDUE: "Overdue",
    DRAFT: "Draft",
    PUBLISHED: "Published",
    ONLINE: "Online",
    OFFLINE: "Offline",
    OPEN: "Open",
    CLOSED: "Closed",
    LIVE: "Live",
  },
  NAVIGATION: {
    DASHBOARD: "Dashboard",
    ORDERS: "Orders",
    PRODUCTS: "Products",
    CATEGORIES: "Categories",
    STAFF: "Staff",
    CUSTOMERS: "Customers",
    REPORTS: "Reports",
    SETTINGS: "Settings",
    LOGOUT: "Log Out",
    PROFILE: "Profile",
    BILLING: "Billing",
    HELP: "Help & Support",
    DOCS: "Documentation",
    ADMIN: "Admin",
    POS: "POS App",
    KITCHEN: "Kitchen Display",
    INVENTORY: "Inventory",
    DISCOUNTS: "Discounts",
    LOYALTY: "Loyalty",
    GIFT_CARDS: "Gift Cards",
    LOCATIONS: "Locations",
    ROLES: "Roles & Permissions",
  },
  DASHBOARD: {
    GREETING_MORNING: "Good Morning",
    GREETING_AFTERNOON: "Good Afternoon",
    GREETING_EVENING: "Good Evening",
    STATS: {
      REVENUE: "Total Revenue",
      ORDERS: "Total Orders",
      CUSTOMERS: "New Customers",
      AVG_ORDER: "Average Order",
      SALES_TREND: "Sales Trend",
      TOP_ITEMS: "Top Selling Items",
      RECENT_ACTIVITY: "Recent Activity",
    }
  },
  FORMS: {
    LABELS: {
      NAME: "Name",
      EMAIL: "Email Address",
      PHONE: "Phone Number",
      PASSWORD: "Password",
      CONFIRM_PASSWORD: "Confirm Password",
      ADDRESS: "Address",
      CITY: "City",
      COUNTRY: "Country",
      ZIP: "Zip / Postal Code",
      DESCRIPTION: "Description",
      PRICE: "Price",
      COST: "Cost",
      QUANTITY: "Quantity",
      CATEGORY: "Category",
      ROLE: "Role",
      STATUS: "Status",
      IMAGE: "Image",
      NOTES: "Notes",
      DATE: "Date",
      TIME: "Time",
    },
    PLACEHOLDERS: {
      SELECT: "Select...",
      SEARCH: "Type to search...",
      ENTER_NAME: "Enter name",
      ENTER_EMAIL: "Enter email address",
      ENTER_PHONE: "Enter phone number",
    },
    VALIDATION: {
      REQUIRED: "This field is required",
      INVALID_EMAIL: "Please enter a valid email",
      INVALID_PHONE: "Please enter a valid phone number",
      PASSWORD_MISMATCH: "Passwords do not match",
      MIN_LENGTH: "Must be at least {0} characters",
      MAX_LENGTH: "Must be no more than {0} characters",
    }
  },
  MODALS: {
    CONFIRM_DELETE: {
      TITLE: "Are you sure?",
      MESSAGE: "This action cannot be undone. This will permanently delete the selected item.",
      CONFIRM: "Yes, Delete",
      CANCEL: "No, Keep",
    },
    UNSAVED_CHANGES: {
      TITLE: "Unsaved Changes",
      MESSAGE: "You have unsaved changes. Are you sure you want to leave?",
      CONFIRM: "Leave",
      CANCEL: "Stay",
    }
  },
  AUTH: {
    LOGIN: {
      TITLE: "Welcome Back",
      SUBTITLE: "Sign in to your account",
      BUTTON: "Sign In",
      FORGOT_PASSWORD: "Forgot Password?",
      NO_ACCOUNT: "Don't have an account?",
      SIGN_UP: "Sign up",
    },
    SIGNUP: {
      TITLE: "Create Account",
      SUBTITLE: "Get started with PayMint",
      BUTTON: "Create Account",
      HAS_ACCOUNT: "Already have an account?",
      SIGN_IN: "Sign in",
    },
    LOGOUT: {
      TITLE: "Logging Out",
      MESSAGE: "Are you sure you want to log out?",
    }
  }
};
